changed again

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,16 +34,13 @@ jobs:
             # Check if the directory is a git repository
             if [ ! -d .git ]; then
               # Clone the repository if not a git repository
-              git clone https://github.com/Kim-Avillanosa/bill-tracker.git .  # Replace with actual repository URL
+              git clone https://github.com/Kim-Avillanosa/bill-tracker.git .  # Replace <repository-url> with the actual repository URL
             else
               # Pull the latest changes if it is a git repository
               git pull origin main || { echo "Git pull failed"; exit 1; }
             fi
 
-            # Bring down the services without affecting MySQL
             docker-compose down || { echo "Docker-compose down failed"; exit 1; }
-
-            # Start up the services, connecting to the existing MySQL container
             docker-compose up -d --build || { echo "Docker-compose up failed"; exit 1; }
           EOF
 
@@ -56,6 +53,6 @@ jobs:
             # Navigate to the directory
             cd /bill-tracker/app || { echo "Failed to change directory"; exit 1; }
 
-            # Start up the services, connecting to the existing MySQL container
+            docker-compose down || { echo "Docker-compose down failed"; exit 1; }
             docker-compose up -d --build || { echo "Docker-compose up failed"; exit 1; }
           EOF
