changed arrangement

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,10 +28,7 @@ jobs:
             # Check if the directory exists; if not, create it
             [ ! -d /bill-tracker/api ] && mkdir -p /bill-tracker/api
             
-            # Navigate to the directory
-            cd /bill-tracker/api || { echo "Failed to change directory"; exit 1; }
-
-            # Check if the directory is a git repository
+              # Check if the directory is a git repository
             if [ ! -d .git ]; then
               # Clone the repository if not a git repository
               git clone https://github.com/Kim-Avillanosa/bill-tracker.git . 
@@ -39,6 +36,11 @@ jobs:
               # Pull the latest changes if it is a git repository
               git pull origin main || { echo "Git pull failed"; exit 1; }
             fi
+
+            # Navigate to the directory
+            cd /bill-tracker/api || { echo "Failed to change directory"; exit 1; }
+
+            
 
             # Check for docker-compose.yml
             if [ ! -f docker-compose.yml ]; then
